global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'lpbot-railway'
    environment: 'production'

scrape_configs:
  # LP Bot metrics
  - job_name: 'lpbot'
    metrics_path: '/metrics'
    scheme: https
    static_configs:
      - targets: ['dinamic-lp-production-f67d.up.railway.app']
        labels:
          service: 'lpbot'
          environment: 'production'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

